# Generated by Django 4.0.4 on 2022-05-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_register_birthday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Birthday_date',
            field=models.DateField(),
        ),
    ]
